import mongoose, { Document, Schema } from 'mongoose';

export interface IWithdrawalRequest extends Document {
  user: mongoose.Types.ObjectId;
  amountCents: number;       // amount in cents
  walletAddress: string;     // user-provided address/bank ID
  status: 'pending' | 'approved' | 'rejected';
  payoutWalletId?: string;   // generated by admin on approval (nanoid 16 chars)
  requestedAt: Date;
  reviewedAt?: Date;
  reviewedBy?: mongoose.Types.ObjectId;
  adminNote?: string;
}

const WithdrawalRequestSchema = new Schema<IWithdrawalRequest>(
  {
    user: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    amountCents: { type: Number, required: true },
    walletAddress: { type: String, required: true },
    status: {
      type: String,
      enum: ['pending', 'approved', 'rejected'],
      default: 'pending',
    },
    payoutWalletId: { type: String },
    requestedAt: { type: Date, default: Date.now },
    reviewedAt: { type: Date },
    reviewedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    adminNote: { type: String },
  },
  { timestamps: true }
);

export default mongoose.model<IWithdrawalRequest>('WithdrawalRequest', WithdrawalRequestSchema);
